Convert `InfoBond::ArpValidate` into an enum.
rust-netlink/netlink-packet-route pull request #110
Opened 2024-04-01 18:51 UTC by Gilnaa

Closes #80

2024-04-01 18:55 UTC, Gilnaa commented on src/link/link_info/bond.rs
> +}
@cathay4t 
In general, does it make sense to add the kernel documentation to these enums?

e.g. based on https://www.kernel.org/doc/html/v6.4-rc7/networking/bonding.html
```suggestion
/// Specifies whether or not ARP probes and replies should be validated in any mode that supports arp monitoring,
/// or whether non-ARP traffic should be filtered (disregarded) for link monitoring purposes.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Default)]
pub enum ArpValidate {
    /// No validation or filtering is performed.
    #[default]
    None,
    /// Validation is performed only for the active slave.
    Active,
    /// Validation is performed only for backup slaves.
    Backup,
    /// Validation is performed for all slaves.
    All,
    /// Filtering is applied to all slaves. No validation is performed.
    Filter,
    /// Filtering is applied to all slaves, validation is performed only for the active slave
    FilterActive,
    /// Filtering is applied to all slaves, validation is performed only for backup slaves.
    FilterBackup,
    Other(u32),
}
```

2024-04-01 19:27 UTC, Gilnaa commented
Also, it seems that these PRs steadily lower the code-coverage.
What meaningful tests can I add?
Run an `ip link add bond0 type bond mode blablablah` and make sure we produce an equivalent output?

2024-04-08 13:22 UTC, cathay4t commented
> Also, it seems that these PRs steadily lower the code-coverage. What meaningful tests can I add? Use `nlmon` to record `ip link add bond0 type bond mode blablablah` and make sure we produce an equivalent output?

I have document on how to capture netlink package and convert it into Vec<u8> at:

https://github.com/rust-netlink/netlink-packet-route/blob/main/README.md

You may setup up a bond with arp_validate value changed to non-default one. Then capture the netlink package kernel replied to the request of `ip -d link show bond0`. The unit test should parse this Vec<u8> into structs/enums, and also `emit()` should generate identical `Vec<u8>` as kernel did.

> 
> Is there place for tests that open an actual socket and try to create rtnl objects; is this problematic with CI running us in a non-privileged context?

For this crate, there is no real netlink communication to kernel. Because this crate only handle parsing and emitting netlink package itself, no socket communication code included. All tests in this crate are unit test, no privilege required.

2024-04-12 13:27 UTC, little-dude commented
@Gilnaa I just added a test in my own MR, in case you want to see how it looks: https://github.com/rust-netlink/netlink-packet-route/pull/98

I used wireshark to get the hex dump of a captured netlink packet, and isolate the different packet parts. It's very tedious, and you don't have to go into so much detail though.

2024-04-24 09:55 UTC, Gilnaa commented
Thank you both!

Unfortunately life got in the way;
will hopefully get back to it eventually

2024-05-26 19:54 UTC, Gilnaa commented
> Unfortunately life got in the way; will hopefully get back to it eventually

Life got out of the way!

I've added a test as instructed; dump is taken of `tcpdump`, with the last few fields removed for brevity, and the length patched in the header.

--- 
I did notice that serializing `stats64` will result in a slightly different payload (I think the length field was different, probably counted padding or something).
Unrelated to this change, though.

2024-08-05 06:17 UTC, cathay4t requested changes

2024-08-05 14:17 UTC, Gilnaa commented on src/link/tests/bond.rs
> +                InfoBond::ArpValidate(ArpValidate::default()),
Done

2024-08-05 14:17 UTC, Gilnaa commented on src/link/tests/bond.rs
> +    assert_eq!(raw, buf);
Ohhh great idea.
Done

2024-09-04 08:54 UTC, cathay4t approved these changes

2024-09-04 08:59 UTC, cathay4t commented
I have amend the patch:
 * Rebased to latest main branch.
 * Changed `enum ArpValidate` to `enum BondArpValidate`.

2024-09-04 09:02 UTC, merged