Add ICMP6_MIB_RATELIMITHOST
rust-netlink/netlink-packet-route pull request #137
Opened 2024-09-21 03:49 UTC by bebecue

2025-01-20 09:06 UTC, cathay4t requested changes
There is `OutRateLimitGlobal` before `OutRateLimitHost`

2025-01-21 05:04 UTC, bebecue commented
As for `OutRateLimitGlobal`, are you talking about [this one in `ICMP_MIB_*`](https://github.com/torvalds/linux/blob/v6.13/include/uapi/linux/snmp.h#L99)?

This PR is about to add one field in [IMCP6_MIB_*](https://github.com/torvalds/linux/blob/v6.13/include/uapi/linux/snmp.h#L106-L120).

2025-05-05 02:18 UTC, cathay4t approved these changes

2025-05-05 02:21 UTC, merged

2025-05-05 02:21 UTC, cathay4t commented
You are correct. Merged! Thanks for the contribution!