Re #19 - Add the nat action to tc
rust-netlink/netlink-packet-route pull request #20
Opened 2023-02-09 21:23 UTC by sophacles

2023-02-16 07:09 UTC, wllenyj approved these changes

2023-02-16 07:11 UTC, wllenyj commented
Please rebase, and solve the ci failure.

2023-02-16 17:59 UTC, sophacles commented
Thanks for taking a look @wllenyj . I've rebased and fixed the formatting errors reported by CI. Will pay attention for additional failures in case I missed something.

2023-02-21 06:33 UTC, wllenyj commented
@cathay4t Do you have any comments?

2023-04-14 08:03 UTC, cathay4t commented
I have ammend the git commit message to include `Signed-off-by: Erich Heine <....>`.

2023-04-14 08:14 UTC, cathay4t requested changes
Besides removing `TCA_NAT_MAX` and PAD, looks good to me.

I am not TC expert, I trust you know your territory

2023-04-14 08:14 UTC, cathay4t commented on src/rtnl/tc/constants.rs
> +pub const TCA_NAT_MAX: u16 = TCA_NAT_PAD;
Please remove `TCA_NAT_PAD` and `TCA_NAT_MAX`.
The `TCA_NAT_PAD` is unused anywhere. The `TCA_NAT_MAX` is not constant to kernel but a internal variable might change in future release of linux kernel.

2023-04-14 08:20 UTC, merged

2023-04-14 13:43 UTC, sophacles commented
> This has been delayed for a long time. Let me amend the patch by removing TCA_NAT_MAX and PAD.

Apoligies, I lost track of that request. Thank you for taking care of  it!