Re #21 - Add matchall filter type
rust-netlink/netlink-packet-route pull request #22
Opened 2023-02-09 21:25 UTC by sophacles

This tc filter matches all packets that encounter it.

2023-02-16 07:18 UTC, wllenyj commented
Thanks, 
Please fix the ci fail.

2023-02-16 18:00 UTC, sophacles commented
Hi, I've rebased and fixed the formatting errors, will pay attention to the next CI run for additonal issues.

2023-02-21 06:30 UTC, wllenyj approved these changes

2023-02-21 06:33 UTC, wllenyj commented
@cathay4t Do you have any comments?

2023-03-26 09:30 UTC, cathay4t requested changes

2023-03-26 09:30 UTC, cathay4t commented on src/rtnl/tc/constants.rs
> +pub const TCA_MATCHALL_MAX: u16 = TCA_MATCHALL_PAD;
Please remove `TCA_MATCHALL_PAD` and `TCA_MATCHALL_MAX`. They are not used in this PR

2023-04-14 08:27 UTC, cathay4t commented
@sophacles Thanks for the patch. I have amended the patch to hold `Signed-off-by:` in git commit message. Next time, please use `git commit --signoff`.

2023-04-14 08:27 UTC, merged